### ISSUE TITLE
Unable Map() ID3D12Resource1: The GPU device instance has been suspended

### ISSUE THREAD

**Issue by SpicyMelonYT** [rdeioris/compushady#4]
Not sure how this error happened but it started randomly and wont stop, please help!

### Error:
```
Traceback (most recent call last):
  File "g:\SMS\LIBRARY\Casual\Compushady\Test_001\scripts\dev_001.py", line 22, in <module>
    run(None)
  File "g:\SMS\LIBRARY\Casual\Compushady\Test_001\scripts\dev_001.py", line 12, in run
    readb = texture.read()
  File "g:\SMS\LIBRARY\Casual\Compushady\Test_001\scripts\core.py", line 49, in read
    return readback_buffer.readback(self.texture.size)
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python310\lib\site-packages\compushady\__init__.py", line 108, in readback
    return self.handle.readback(buffer_or_size, offset)
Exception: Unable Map() ID3D12Resource1: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
```

### My Code:

Error happens in the "readb = texture.read()" line of the testing script below.
That calls a function in my wrapper class in core script below and the error happens here: "readback_buffer.readback(self.texture.size)"

testing script:
```py
import core
import reader


def run(device):
    texture = core.GPUTexture(8, 8)

    print("DWADWAADW")

    texture.compute(reader.read_hlsl_file("shader_001.hlsl"))

    readb = texture.read() # ERROR HAPPENS HERE

    pixels = []

    for i in range(int(texture.size / 4)):
        j = i * 4
        pixels.append((readb[j + 0], readb[j + 1], readb[j + 2], readb[j + 3]))

    print(pixels)

```

core script
```py
from compushady import Buffer, Texture2D, HEAP_UPLOAD, HEAP_READBACK, Compute
import compushady.formats as csformats
from compushady.shaders import hlsl
import re


class GPUTexture:
    def __init__(self, width=8, height=8) -> None:
        self.device = None
        self.format = csformats.R8G8B8A8_UINT
        self.create_texture(width, height)
        self.create_staging_buffer()
        self.write()

    @property
    def width(self):
        return self.texture.width

    @property
    def height(self):
        return self.texture.height

    @property
    def size(self):
        return self.texture.size

    def create_texture(self, width=8, height=8):
        self.texture = Texture2D(
            width, height, format=self.format, device=self.device)

    def create_staging_buffer(self):
        self.staging_buffer = self.create_buffer()

    def create_buffer(self):
        return Buffer(
            self.texture.size, HEAP_UPLOAD, format=self.format, device=self.device)

    def upload(self, data: bytes):
        return self.staging_buffer.upload(data)

    def write(self, texture=None):
        if texture is None:
            texture = self.texture
        return self.staging_buffer.copy_to(texture)

    def read(self):
        readback_buffer = self.create_buffer()
        self.texture.copy_to(readback_buffer)
        return readback_buffer.readback(self.texture.size)

    def compute(self, shader):
        compiled = hlsl.compile(shader)
        compute = Compute(compiled, uav=[
                          self.texture], device=self.device)
        numgroups = self.get_numthreads(shader)

        nx = 2
        ny = 2

        if numgroups is not None:
            nx = numgroups[0]
            ny = numgroups[1]

        compute.dispatch(self.texture.width // nx,
                         self.texture.height // ny, 1)

    def get_numthreads(self, shader):
        # Search for the numthreads attribute in the shader code
        match = re.search(r'\[numthreads\((\d+), (\d+), (\d+)\)\]', shader)

        # If the numthreads attribute is found, return it as a tuple of integers
        if match:
            return tuple(map(int, match.groups()))

        # If the numthreads attribute is not found, return None
        return None

```

**Comment by rdeioris** [comment]
It looks like you are creating the readback buffer as a HEAP_UPLOAD instead of HEAP_READBACK

**Comment by SpicyMelonYT** [comment]
Ahhhhh right, thank you. That is a very dumb oversight from me. Thanks for helping. I would normally not post a question like that but I just really couldn't figure it out at all. Sorry and thanks!
