### ISSUE TITLE
SampleLevel SamplerState Issue

### ISSUE THREAD

**Issue by DigiTecK3D** [rdeioris/compushady#6]
Hello I'm currently working on a compute shader and I'm doing a sampling step in the compute shader, right now I'm unsure how or if compushady can do samplerstate for sampling the texture. When I run this code

```
SamplerState gSampler : register(s0);

// Function to get height from the height map at specified coordinates and level
float getH(float2 uv, int srcLevel)
{
    return heightMap.SampleLevel(gSampler, uv, srcLevel).r;
}
```

I will get this error in the Python output

```
Traceback (most recent call last):
  File "C:\Users\miguel.santiago\Desktop\PythonConeStep\compushade_06.py", line 222, in <module>
    compute = Compute(hlsl.compile(shader_source), srv=[source_texture], uav=[destination_texture])
  File "C:\Users\miguel.santiago\Desktop\PythonConeStep\myenv\lib\site-packages\compushady\__init__.py", line 222, in __init__
    uav=[resource.handle for resource in uav])
Exception: Unable to create Compute Pipeline State: The parameter is incorrect.

ID3D12Device::CreateComputePipelineState: Root Signature doesn't match Compute Shader: Shader sampler descriptor range (BaseShaderRegister=0, NumDescriptors=1, RegisterSpace=0) is not fully bound in root signature
```

**Comment by rdeioris** [comment]
Hi, you can try the sampler branch, it includes an example: https://github.com/rdeioris/compushady/blob/samplers/examples/simple_sampler.py

**Comment by rdeioris** [comment]
@DigiTecK3D samplers support has been merged in latest stable release
